name: admin_panel
description: Admin Panel Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.0
  local_auth: ^3.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  google_fonts: ^8.1.0
  shared_preferences: ^2.2.3
  flutter_dotenv: ^6.0.1
  shimmer: ^3.0.0
  fl_chart: ^1.2.0
  local_auth_android: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
